### ISSUE TITLE
Not working for Android SDK <29

### ISSUE THREAD

**Issue by pamafe1976** [natsuk4ze/compassx#14]
### Did you check the documentation and it did not help?

- [X] I have read the [README](https://github.com/natsuk4ze/compassx/blob/main/README.md)
- [X] I have searched the [existing documentation](https://github.com/natsuk4ze/compassx/wiki)
- [X] I have read the [contribution guide](https://github.com/natsuk4ze/compassx/blob/main/CONTRIBUTING.md)

### Overview

Hi,
This is a nice package and it works fine on iOS and Android >= 29.
However it should be fixed asap for Android < 29
Regards

### Steps to reproduce

Just add the package to pubspec.yaml, and use minSdkVersion less than 29 in build.gradle

The moment you allow location permission you will get:
```

D/AndroidRuntime(11849): Shutting down VM
E/AndroidRuntime(11849): FATAL EXCEPTION: main
E/AndroidRuntime(11849): Process: com.example.testgeolocator, PID: 11849
E/AndroidRuntime(11849): java.lang.AbstractMethodError: abstract method "void android.location.LocationListener.onStatusChanged(java.lang.String, int, android.os.Bundle)"
E/AndroidRuntime(11849): 	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:378)
E/AndroidRuntime(11849): 	at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:300)
E/AndroidRuntime(11849): 	at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:316)
E/AndroidRuntime(11849): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(11849): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(11849): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(11849): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11849): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(11849): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Environment

[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale es-AR)
    • Flutter version 3.19.6 on channel stable at /Users/pablo/Proyectos/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (4 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/pablo/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/pablo/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/pablo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.89.20240501

[✓] Connected device (4 available)
    • Android SDK built for arm64 (mobile) • emulator-5554             • android-arm64  • Android 9 (API 28) (emulator)
    • iPhone de Pablo (mobile)             • 00008110-001E38D03651801E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)                      • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                         • chrome                    • web-javascript • Google Chrome 124.0.6367.207

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by pamafe1976** [comment]
Looks like you have to override onStatusChanged to be compatible with Android < 29

[(https://developer.android.com/reference/android/location/LocationListener#onStatusChanged(java.lang.String,%20int,%20android.os.Bundle))]

**Comment by natsuk4ze** [comment]
I just published the new version, thank you for your contribution😊 @pamafe1976
