### ISSUE TITLE
How to solve not support sensor

### ISSUE THREAD

**Issue by AndyAls** [natsuk4ze/compassx#22]
### Did you check the documentation and it did not help?

- [X] I have carefully read the [README](https://github.com/natsuk4ze/compassx/blob/main/README.md)
- [X] I have carefully searched the [existing documentation](https://github.com/natsuk4ze/compassx/wiki)
- [X] I have carefully read the [contribution guide](https://github.com/natsuk4ze/compassx/blob/main/CONTRIBUTING.md)

### Proposal

`CompassX.events.listen((event) {},onError: (e) {}`
onError not call

### Use case

`CompassX.events.listen((event) {},onError: (e) {}`
onError not call

**Comment by natsuk4ze** [comment]
Works well on my env.

```dart
CompassX.events.listen((_){}, onError: (e) => log(e.toString()));
```

```log
[log] [CompassXException/SENSOR_NOT_FOUND]: Compass sensor not found.
```

Unless you provide more detailed information and reproducible code, we cannot support you.
